### ISSUE TITLE
Color changes back to default on press or leaving activity

### ISSUE THREAD

**Issue by demandedcross** [shamanland/floating-action-button#18]
Not sure if this is a bug or something I'm doing wrong. I'm setting the color usin palette after glide has finished loading an image resource from a url into the view. The color is set correctly but then changes to a default gray color after it is clicked or just before the activity disappears and stays that color.

**Comment by shomeser** [comment]
Do you want to change the color of button during runtime? If not, try to customize it via styles, like [here][1].

It's hard to understand what you are doing without code examples.

 [1]: https://github.com/shamanland/floating-action-button/blob/master/app/src/main/res/values/styles.xml

**Comment by demandedcross** [comment]
Yeah it's during runtime, using the Palette api to get the colour from a bitmap loaded from a url.
```
Glide.with(App.me).load(coverUrl).asBitmap().thumbnail(0.2f).animate(R.anim.abc_fade_in).into(new BitmapImageViewTarget(movieDetailCoverImage) {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                        super.onResourceReady(bitmap, anim);

                        Palette.generateAsync(bitmap, new Palette.PaletteAsyncListener() {
                            public void onGenerated(Palette palette) {
                                // Do something with colors...
                                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                                    getWindow().setStatusBarColor(palette.getDarkVibrantColor(Color.GRAY));
                                }

                                fab.setColor(palette.getVibrantColor(Color.GRAY));
                                fab.initBackground();


                            }
                        });
                    }
                });
```

**Comment by shomeser** [comment]
Try to add this before `setColor()`:

    fab.setColorStateList(null);

If this line will help, than I will fix the bug.

**Comment by demandedcross** [comment]
That fixes it :)

**Comment by shomeser** [comment]
Okay, you may use this workaround, and I will fix it soon.
